version: "2"
services:
  mysql:
    image: manaphp/dmysql
    ports:
      - 3306:3306
    restart: always
  mongodb:
    image: manaphp/dmongodb
    ports:
      - 27017:27017
    restart: always
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
