version: "2"
services:
  api_fpm:
    image: manaphp/php73:2.0
    volumes:
      - ../:/var/www/html
      - ./fpm/conf.d:/etc/php/conf.d
      - /data/volumes/${COMPOSE_PROJECT_NAME}/api/fpm:/var/log/php
      - /data/volumes/${COMPOSE_PROJECT_NAME}/api/app/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/api/app/tmp:/var/www/html/tmp
    restart: always
  api_nginx:
    image: nginx:1.17.1
    volumes:
      - ../:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/volumes/${COMPOSE_PROJECT_NAME}/api/nginx:/var/log/nginx
    ports:
      - ${WEB_PORT}:80
    restart: always