version: "2"
services:
  api_swoole:
    image: manaphp/php72:1.2
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ../:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/api/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/api/tmp:/var/www/html/tmp
    command: php /var/www/html/public/index.php
    ports:
      - ${WEB_PORT}:9501
    restart: always
  redis:
    image: redis:4.0.14
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - /data/volumes/${COMPOSE_PROJECT_NAME}/redis/data/:/data/
      - ./redis/conf:/etc/redis
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server /etc/redis/redis.conf
    restart: always  